/** Predefined MovieKart curated collection definitions (seeded into MongoDB). */
export const CURATED_COLLECTION_DEFS = [
  {
    slug: "mcu-complete-watch-order",
    title: "MCU Complete Watch Order",
    description:
      "The definitive Marvel Cinematic Universe checklist — Infinity Saga through the Multiverse Saga in release order, including Disney+ series and announced upcoming projects.",
    category: "Franchise",
    featured: true,
    tags: ["Marvel", "Action", "Superhero", "Disney+"],
    mediaType: "mixed",
    popularity: 100,
    itemsVersion: 2,
    plannedTitles: [
      "Blade",
      "Shang-Chi 2",
      "X-Men",
      "Armor Wars",
      "Doctor Strange 3",
      "Thor 5",
      "Eternals 2",
    ],
    items: [
      // Phase 1 — The Avengers Initiative
      1726, 1724, 10138, 10195, 1771, 24428,
      // Phase 2
      68721, 76338, 100402, 118340, 99861, 102899,
      // Phase 3 — Infinity Saga finale
      271110, 284052, 283995, 315635, 284053, 284054, 299536, 363088, 299537, 299534, 429617,
      // Phase 4 — Movies
      497698, 566525, 524434, 634649, 453395, 616037, 505642,
      // Phase 4 — Disney+ shows & specials
      -85271, -88396, -84958, -91363, -88329, -92749, -92783, -92782, 894205, 774752,
      // Phase 5 — Movies
      640146, 447365, 609681, 533535, 822119, 986056,
      // Phase 5 — Shows (Loki S2 & What If S2 reuse series IDs)
      -114472, -84958, -91363, -122226, -138501, -202555, -114471,
      // Phase 6 — Released & announced
      617126, -198178, 969681, -213375, 1003596, -202555, 1003598,
      // TBD with TMDB placeholder pages
      1386618,
    ],
  },
  {
    slug: "dc-universe-essentials",
    title: "DC Universe Essentials",
    description: "The definitive DC superhero journey — from Man of Steel to the latest epics.",
    category: "Franchise",
    featured: true,
    tags: ["DC", "Action", "Superhero"],
    mediaType: "movie",
    popularity: 95,
    discoverPath: "/discover/movie?with_companies=9993|429|174&sort_by=popularity.desc&vote_count.gte=200",
    limit: 20,
  },
  {
    slug: "harry-potter-collection",
    title: "Harry Potter Collection",
    description: "All eight magical films following the Boy Who Lived at Hogwarts.",
    category: "Franchise",
    featured: true,
    tags: ["Fantasy", "Adventure", "Family"],
    mediaType: "movie",
    popularity: 98,
    items: [671, 672, 673, 674, 675, 767, 12444, 12445],
  },
  {
    slug: "lord-of-the-rings-hobbit-saga",
    title: "Lord of the Rings & Hobbit Saga",
    description: "Middle-earth in full — the complete Rings trilogy and Hobbit films.",
    category: "Franchise",
    featured: true,
    tags: ["Fantasy", "Epic", "Adventure"],
    mediaType: "movie",
    popularity: 97,
    items: [120, 121, 122, 49026, 49051, 122917],
  },
  {
    slug: "fast-and-furious-collection",
    title: "Fast & Furious Collection",
    description: "Family, fuel, and high-octane heists — the full Fast saga.",
    category: "Franchise",
    featured: false,
    tags: ["Action", "Racing", "Thriller"],
    mediaType: "movie",
    popularity: 88,
    discoverPath: "/search/movie?query=Fast%20%26%20Furious&sort_by=release_date.asc",
    limit: 12,
  },
  {
    slug: "mission-impossible-collection",
    title: "Mission Impossible Collection",
    description: "Ethan Hunt's impossible missions — every death-defying entry.",
    category: "Franchise",
    featured: false,
    tags: ["Action", "Spy", "Thriller"],
    mediaType: "movie",
    popularity: 85,
    items: [954, 955, 956, 177677, 353081, 575264, 575265, 298618],
  },
  {
    slug: "james-bond-collection",
    title: "James Bond Collection",
    description: "Shaken, not stirred — essential 007 adventures across the decades.",
    category: "Franchise",
    featured: false,
    tags: ["Action", "Spy", "Classic"],
    mediaType: "movie",
    popularity: 82,
    discoverPath: "/search/movie?query=James%20Bond&sort_by=popularity.desc",
    limit: 15,
  },
  {
    slug: "top-imdb-250-essentials",
    title: "Top IMDb 250 Essentials",
    description: "Critically acclaimed masterpieces that define cinema history.",
    category: "Essentials",
    featured: true,
    tags: ["Drama", "Classic", "Award-Winning"],
    mediaType: "movie",
    popularity: 96,
    discoverPath: "/movie/top_rated?page=1",
    limit: 25,
  },
  {
    slug: "oscar-winners-collection",
    title: "Oscar Winners Collection",
    description: "Academy Award-winning films celebrated for excellence in filmmaking.",
    category: "Essentials",
    featured: true,
    tags: ["Drama", "Award-Winning", "Prestige"],
    mediaType: "movie",
    popularity: 90,
    discoverPath: "/discover/movie?sort_by=vote_average.desc&vote_count.gte=1000&with_release_type=2|3",
    limit: 25,
  },
  {
    slug: "best-sci-fi-movies",
    title: "Best Sci-Fi Movies",
    description: "Mind-bending futures, space odysseys, and visionary science fiction.",
    category: "Genre",
    featured: true,
    tags: ["Sci-Fi", "Space", "Future"],
    mediaType: "movie",
    popularity: 92,
    discoverPath: "/discover/movie?with_genres=878&sort_by=vote_average.desc&vote_count.gte=500",
    limit: 25,
  },
  {
    slug: "best-horror-movies",
    title: "Best Horror Movies",
    description: "Terrifying classics and modern nightmares that will keep you up at night.",
    category: "Genre",
    featured: false,
    tags: ["Horror", "Thriller", "Scary"],
    mediaType: "movie",
    popularity: 87,
    discoverPath: "/discover/movie?with_genres=27&sort_by=vote_average.desc&vote_count.gte=500",
    limit: 25,
  },
  {
    slug: "best-anime-movies",
    title: "Best Anime Movies",
    description: "Stunning animation from Studio Ghibli, Makoto Shinkai, and beyond.",
    category: "Genre",
    featured: false,
    tags: ["Anime", "Animation", "Japanese"],
    mediaType: "movie",
    popularity: 86,
    items: [129, 4935, 10681, 16859, 995456, 372058, 149871, 1184918, 15283, 9806],
    discoverPath: "/discover/movie?with_genres=16&with_original_language=ja&sort_by=vote_average.desc&vote_count.gte=200",
    limit: 20,
  },
  {
    slug: "christopher-nolan-collection",
    title: "Christopher Nolan Collection",
    description: "Every mind-bending masterpiece from one of cinema's greatest auteurs.",
    category: "Director",
    featured: true,
    tags: ["Nolan", "Thriller", "Sci-Fi"],
    mediaType: "movie",
    popularity: 94,
    items: [1124, 77, 272, 49026, 27205, 135397, 157336, 374720, 419430, 577922],
  },
  {
    slug: "marvel-multiverse-saga",
    title: "Marvel Multiverse Saga",
    description: "Phase 4 and beyond — the Multiverse Saga unfolds across dimensions.",
    category: "Franchise",
    featured: true,
    tags: ["Marvel", "Multiverse", "Superhero"],
    mediaType: "movie",
    popularity: 93,
    items: [
      566525, 634649, 453395, 616037, 609681, 822119, 533535, 617126, 940721,
      1090846,
    ],
  },
  {
    slug: "spider-man-across-universes",
    title: "Spider-Man Across Universes",
    description: "Every Spider-Man adventure — live action and animated multiverse tales.",
    category: "Franchise",
    featured: false,
    tags: ["Marvel", "Spider-Man", "Animation"],
    mediaType: "mixed",
    popularity: 91,
    items: [557, 1930, 315635, 429617, 634649, 569094, 453395, 808],
  },
  {
    slug: "best-movies-of-the-2020s",
    title: "Best Movies of the 2020s",
    description: "The defining films of the decade — so far.",
    category: "Decade",
    featured: true,
    tags: ["2020s", "Modern", "Trending"],
    mediaType: "movie",
    popularity: 89,
    discoverPath: "/discover/movie?primary_release_date.gte=2020-01-01&primary_release_date.lte=2029-12-31&sort_by=vote_average.desc&vote_count.gte=500",
    limit: 30,
  },
  {
    slug: "greatest-tv-shows-of-all-time",
    title: "Greatest TV Shows of All Time",
    description: "Binge-worthy series that redefined television storytelling.",
    category: "TV",
    featured: true,
    tags: ["TV", "Drama", "Binge"],
    mediaType: "tv",
    popularity: 99,
    discoverPath: "/tv/top_rated?page=1",
    limit: 25,
    tvItems: true,
  },
];
